# Generated by Django 5.0.7 on 2024-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='text',
            field=models.TextField(default='I hacked this world', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='publicationcomment',
            name='user_name',
            field=models.CharField(default='anonymous', max_length=50, verbose_name='Имя автора'),
        ),
    ]
