# Generated by Django 5.0.7 on 2024-08-07 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0002_publicationcomment_text_publicationcomment_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
