# Generated by Django 5.0.7 on 2024-08-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0003_publicationcomment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcomment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='typography.publication', verbose_name='Публикация'),
        ),
    ]
