# Generated by Django 5.0.7 on 2024-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0005_category_publication_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='publication',
            name='is_hidden',
            field=models.BooleanField(default=True, verbose_name='Скрыта'),
        ),
    ]
