# Generated by Django 5.0.7 on 2024-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0006_alter_publicationcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыта'),
        ),
    ]
