# Generated by Django 5.0.7 on 2024-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0007_alter_publication_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('email_name', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
