# Generated by Django 5.0.7 on 2024-08-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0009_rename_email_name_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Полное содержание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Полное содержание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
